fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: idjobs@mail.idweaver.net
    sender_name: User
  service:
    mailer: fos_user.mailer.twig_swift
