<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pucutI2' shared service.

return $this->privates['.service_locator.pucutI2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'translationManager' => ['privates', 'App\\Service\\TranslationManager', 'getTranslationManagerService.php', true],
], [
    'translationManager' => 'App\\Service\\TranslationManager',
]);
