<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ajfOkS9' shared service.

return $this->privates['.service_locator.ajfOkS9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'survey' => ['privates', '.errored..service_locator.ajfOkS9.App\\Entity\\Survey', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\Survey" but no such service exists.'],
    'translationManager' => ['privates', 'App\\Service\\TranslationManager', 'getTranslationManagerService.php', true],
], [
    'em' => '?',
    'survey' => 'App\\Entity\\Survey',
    'translationManager' => 'App\\Service\\TranslationManager',
]);
