<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.manager.translation' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/TranslationManager.php';

return $this->services['app.manager.translation'] = new \App\Service\TranslationManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), 'fr|nl', 'en');
