<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.I3J_4QW' shared service.

return $this->privates['.service_locator.I3J_4QW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'notificationManager' => ['services', 'App\\Service\\NotificationManager', 'getNotificationManagerService.php', true],
    'scoreCalculator' => ['privates', 'App\\Service\\StatsCalculator', 'getStatsCalculatorService.php', true],
    'translationManager' => ['privates', 'App\\Service\\TranslationManager', 'getTranslationManagerService.php', true],
], [
    'manager' => '?',
    'notificationManager' => 'App\\Service\\NotificationManager',
    'scoreCalculator' => 'App\\Service\\StatsCalculator',
    'translationManager' => 'App\\Service\\TranslationManager',
]);
