<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bPeIlWj' shared service.

return $this->privates['.service_locator.bPeIlWj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'notificationManager' => ['services', 'App\\Service\\NotificationManager', 'getNotificationManagerService.php', true],
], [
    'em' => '?',
    'notificationManager' => 'App\\Service\\NotificationManager',
]);
