<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.w8wW8Yt' shared service.

return $this->privates['.service_locator.w8wW8Yt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'quizAnswer' => ['privates', '.errored..service_locator.w8wW8Yt.App\\Entity\\QuizAnswer', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\QuizAnswer" but no such service exists.'],
], [
    'manager' => '?',
    'quizAnswer' => 'App\\Entity\\QuizAnswer',
]);
