<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.T15j7tn' shared service.

return $this->privates['.service_locator.T15j7tn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'surveyAnswer' => ['privates', '.errored..service_locator.T15j7tn.App\\Entity\\SurveyAnswer', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\SurveyAnswer" but no such service exists.'],
], [
    'manager' => '?',
    'surveyAnswer' => 'App\\Entity\\SurveyAnswer',
]);
