<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NS0bXSc' shared service.

return $this->privates['.service_locator.NS0bXSc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'answerRepository' => ['privates', 'App\\Repository\\AnswerRepository', 'getAnswerRepositoryService.php', true],
    'quizAnswer' => ['privates', '.errored..service_locator.NS0bXSc.App\\Entity\\QuizAnswer', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\QuizAnswer" but no such service exists.'],
    'scoreCalculator' => ['privates', 'App\\Service\\ScoreCalculator', 'getScoreCalculatorService.php', true],
], [
    'answerRepository' => 'App\\Repository\\AnswerRepository',
    'quizAnswer' => 'App\\Entity\\QuizAnswer',
    'scoreCalculator' => 'App\\Service\\ScoreCalculator',
]);
