<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rkoEe7W' shared service.

return $this->privates['.service_locator.rkoEe7W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repoQuiz' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService.php', true],
    'repoSurv' => ['privates', 'App\\Repository\\SurveyRepository', 'getSurveyRepositoryService.php', true],
    'translationManager' => ['privates', 'App\\Service\\TranslationManager', 'getTranslationManagerService.php', true],
], [
    'repoQuiz' => 'App\\Repository\\QuizRepository',
    'repoSurv' => 'App\\Repository\\SurveyRepository',
    'translationManager' => 'App\\Service\\TranslationManager',
]);
