<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.flash_listener' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/FlashListener.php';

return $this->privates['app.flash_listener'] = new \App\EventListener\FlashListener(($this->services['session'] ?? $this->load('getSessionService.php')));
