<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.6cFgvLw.App\Entity\Answer' shared service.

include_once $this->targetDirs[3].'/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Translatable.php';
include_once $this->targetDirs[3].'/src/Entity/Answer.php';

return $this->privates['.errored..service_locator.6cFgvLw.App\\Entity\\Answer'] = new \App\Entity\Answer();
