<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Quiz extends \App\Entity\Quiz implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'categories', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'quizAnswers', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'sendingEmail', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'sendingEmailLanguage', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'locale', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'titleFr', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'titleNl', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'descriptionFr', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'descriptionNl'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'categories', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'quizAnswers', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'sendingEmail', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'sendingEmailLanguage', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'locale', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'titleFr', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'titleNl', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'descriptionFr', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'descriptionNl'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Quiz $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriesName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriesName', []);

        return parent::getCategoriesName();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\App\Entity\QuizCategory $quizCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', [$quizCategory]);

        return parent::addCategory($quizCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\App\Entity\QuizCategory $quizCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', [$quizCategory]);

        return parent::removeCategory($quizCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuizAnswers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuizAnswers', []);

        return parent::getQuizAnswers();
    }

    /**
     * {@inheritDoc}
     */
    public function addQuizAnswer(\App\Entity\QuizAnswer $quizAnswer): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuizAnswer', [$quizAnswer]);

        return parent::addQuizAnswer($quizAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuizAnswer(\App\Entity\QuizAnswer $quizAnswer): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuizAnswer', [$quizAnswer]);

        return parent::removeQuizAnswer($quizAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendingEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendingEmail', []);

        return parent::getSendingEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendingEmail(string $sendingEmail): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendingEmail', [$sendingEmail]);

        return parent::setSendingEmail($sendingEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendingEmailLanguage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendingEmailLanguage', []);

        return parent::getSendingEmailLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendingEmailLanguage(string $sendingEmailLanguage): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendingEmailLanguage', [$sendingEmailLanguage]);

        return parent::setSendingEmailLanguage($sendingEmailLanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setTranslatableLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTranslatableLocale', [$locale]);

        return parent::setTranslatableLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleFr(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleFr', []);

        return parent::getTitleFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleFr($titleFr): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleFr', [$titleFr]);

        return parent::setTitleFr($titleFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleNl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleNl', []);

        return parent::getTitleNl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleNl($titleNl): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleNl', [$titleNl]);

        return parent::setTitleNl($titleNl);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionFr(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionFr', []);

        return parent::getDescriptionFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionFr($descriptionFr): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionFr', [$descriptionFr]);

        return parent::setDescriptionFr($descriptionFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionNl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionNl', []);

        return parent::getDescriptionNl();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionNl($descriptionNl): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionNl', [$descriptionNl]);

        return parent::setDescriptionNl($descriptionNl);
    }

}
