<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMuuY9Ji\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMuuY9Ji/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMuuY9Ji.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMuuY9Ji\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMuuY9Ji\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MuuY9Ji',
    'container.build_id' => '7bf12fd2',
    'container.build_time' => 1561594165,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMuuY9Ji');
