<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMJ5MVKD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMJ5MVKD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMJ5MVKD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMJ5MVKD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMJ5MVKD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MJ5MVKD',
    'container.build_id' => '6551d356',
    'container.build_time' => 1561611806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMJ5MVKD');
