<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'js/app' => [
            'js' => [
                '/build/js/app.fc956659.js',
            ],
        ],
        'js/survey' => [
            'js' => [
                '/build/js/survey.750b98df.js',
            ],
        ],
        'js/question' => [
            'js' => [
                '/build/js/question.d3c91278.js',
            ],
        ],
        'css/app' => [
            'css' => [
                '/build/css/app.9b0f461b.css',
            ],
        ],
    ],
],

]];
